### ISSUE TITLE
abstract type overhead

### ISSUE THREAD

**Issue by zmiimz** [szaghi/DEFY#1]
Dear Stefano,
I would like to see your gist here 
https://gist.github.com/szaghi/1946cd7ddabc1a9cb851

and from my side - m.b. simple but funny timing code for newbies ( and compiler optimization performance tests )
https://gist.github.com/zmiimz/1e85ea37e3b02226068ad4b3f2ba41c4

**Comment by szaghi** [comment]
@zmiimz Thank you a lot very nice!

**Comment by szaghi** [comment]
Added! https://github.com/szaghi/DEFY/tree/master/src/powers_naive_definitions_have_overhead

I would really appreciate if you want to fill your test description: if you like I can give you full access to repository.
